name: Deploy to Dev

on:
  workflow_dispatch:  # Allow manual triggering of the workflow
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        run: |
          gcloud auth activate-service-account --key-file=.github/workflows/gcloud.json
          gcloud config set project garnet-cs-website
          gcloud auth list

      - name: Deploy to Google Cloud Storage
        run: |
          gsutil -m rsync -r ./ gs://garnetcs-temp/
