name: Deploy to GCS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GCP credentials
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcloud.json
      run: |
        echo "${{ secrets.GCP0 }}" > $GOOGLE_APPLICATION_CREDENTIALS
        echo "Credentials saved to: $GOOGLE_APPLICATION_CREDENTIALS"
        cat $GOOGLE_APPLICATION_CREDENTIALS  # Optional: Print for debug (remove for security)

    - name: Validate Key File
      run: |
        echo "Validating key file..."
        cat ${{ runner.temp }}/gcloud.json
        jq '.' ${{ runner.temp }}/gcloud.json
   
    - name: Authenticate with GCP
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcloud.json
      run: |
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        gcloud config set project garnet-cs-website

    - name: Test GCP Authentication
      run: |
        gcloud auth list
        gcloud storage buckets list

    - name: Deploy files to GCS
      run: |
        gsutil -m rsync -r . gs://garnetcs-temp/
