name: Deploy to GCS

on:
  push:
    branches:
      - main  # Run workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud SDK authentication
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 3: Install Google Cloud CLI (replacing google-cloud-sdk)
      - name: Install Google Cloud CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli

      # Step 4: Sync files to the GCS bucket
      - name: Deploy to GCS
        run: |
          gsutil -m rsync -r . gs://garnetcs-temp/
