name: Deploy to Google Cloud Storage

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GCP credentials
      run: |
        echo "${{ secrets.GCP0 }}" > gcloud.json
        gcloud auth activate-service-account --key-file=gcloud.json

    - name: Set Project
      run: |
        gcloud config set project garnet-cs-website

    - name: Verify Authentication
      run: |
        gcloud auth list
        gcloud config list

    - name: Deploy files to Google Cloud Storage
      run: |
        gsutil -m rsync -r . gs://garnetcs-temp/

    - name: Clean up credentials
      run: rm gcloud.json
